### ISSUE TITLE
Incorrect CSS rule

### ISSUE THREAD

**Issue by TimVevida** [vlastuin/vevida-optimizer#6]
In the stylesheet of the Optimizer, there is the following line:
```
.dashboard_page_vevida-optimizer p, .description {
```
which contains the selector `.description`, which is too generic. It also applies to the descriptions in the Customizer, for example.

What was meant, I think:
```
.dashboard_page_vevida-optimizer p,
.dashboard_page_vevida-optimizer .description {
```

**Comment by BrianStal** [comment]
That was meant! ;)
