### ISSUE TITLE
MyISAM-to-InnoDB conversions

### ISSUE THREAD

**Issue by slomeli79** [vlastuin/vevida-optimizer#8]
Is the conversion functionality in the last version of the Optimizer in the WP repo still safe to use on the latest WP versions? Are you planning to release an offsite version of the plugin, or a standalone conversion tool? Your plugin was absolutely the best and most trusted way I'd found to convert tables.

**Comment by Digiover** [comment]
Thank you for your compliment, great tot hear! I wouldn't recommend to use the Vevida Optimizer anymore, it conflicts with WordPress' own update mechanisms. Therefore, it's no longer available in the [Plugin directory](https://wordpress.org/plugins/search/vevida+optimizer/).

As for the MyISAM to InnoDB convertion plugin: There are no plans to release it as a standalone conversion tool, but the code is up on Github, so you're free it incorporate into your own code (for example).
